---
name: test-retest-action
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [devel]
    paths:
      - 'actions/retest/**'
      - '.github/workflows/test-retest-action.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Docker build
        # Run cd to avoid loading complete cephcsi directory in docker context
        # while building retest image.
        run: cd actions/retest && docker build -t retest .
