---
name: List TODO's
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - devel

permissions:
  contents: read

jobs:
  tickgit:
    name: tickgit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - run: make containerized-test TARGET=tickgit
